require('setup/cocConfig')
require('setup/vimtex')
require('setup/vimwiki')
require('setup/airline')
require('setup/barbar')
require('setup/treesit')
require('setup/autopair')
require('setup/telescope')
